# name: Deploy CDK Stack
# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: "Select deployment environment"
#         required: true
#         default: "develop"
#         type: choice
#         options:
#           - develop
#           - staging
#           - production
name: Test CDK Deploy
on:
  push:
    branches:
      - add/s3-recovery-stack  


  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "SOURCE_BUCKET_NAME=${{ vars.SOURCE_BUCKET_NAME }}" >> .env
          echo "DESTINATION_BUCKET_NAME=${{ vars.DESTINATION_BUCKET_NAME }}" >> .env
          echo "ALLOW_BATCH_REPLICATION=${{ vars.ALLOW_BATCH_REPLICATION }}" >> .env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Synthesize CloudFormation templates
        run: cdk synth

      - name: Deploy CDK stack
        run: cdk deploy --require-approval never
